cmake_minimum_required(VERSION 3.0.0)

if (NOT BDS_ROOT)
  set(BDS_ROOT "$ENV{BDS}")
endif()
if (NOT BDS_ROOT)
  if(BORLAND AND EMBARCADERO)
    get_filename_component(BDS_ROOT "${CMAKE_C_COMPILER}/../.." ABSOLUTE)
    message(STATUS "Borland root: ${BDS_ROOT}")
  else()
    set(BDS_ROOT "C:/Program Files (x86)/Embarcadero/Studio/18.0")
    message(WARNING "Defaulting to ${BDS_ROOT}, consider running rsvars.bat or assign BDS environment variable.")
  endif()
endif()

if (NOT BDSINCLUDE)
  set(BDSINCLUDE "${BDS_ROOT}/include")
endif()

if (CG_BOOST_ROOT)
  set(BOOST_ROOT "${CG_BOOST_ROOT}")
else()
  set(BOOST_ROOT "$ENV{CG_BOOST_ROOT}")
endif()
if (NOT BOOST_ROOT)
  set(BOOST_ROOT "${BDSINCLUDE}/boost_1_39")
endif()